version: 2.1

orbs:
  gcp-cli: circleci/gcp-cli@2.4.0
  gcp-gcr: circleci/gcp-gcr@0.14.1
  gcp-gke: circleci/gcp-gke@1.4.0
  helm: circleci/helm@1.2.0

parameters:
  appVersion:
    type: string
    default: ""

jobs:
  update-appVersion:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run:
          name: Update appVersion
          command: |
            wget https://github.com/mikefarah/yq/releases/download/v4.20.2/yq_linux_amd64.tar.gz -O - | \
              tar xz && sudo mv yq_linux_amd64 /usr/bin/yq
            IMAGE_TAG=<<pipeline.parameters.appVersion>>
            yq eval --inplace '.image.tag = env(IMAGE_TAG)' values.yaml
            git commit -am 'Update image tag'
  package-chart:
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - gcp-cli/install:
          version: "372.0.0"
      - gcp-cli/initialize
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: $CLUSTER_NAME
          install-kubectl: true
      - run: 
          name: Authenticate with Artifact Registry
          command: |
            cat ${HOME}/gcloud-service-key.json | helm registry login -u _json_key \
              --password-stdin \
              "https://${GOOGLE_COMPUTE_REGION}-docker.pkg.dev"
      - helm/install-helm-client:
          version: "3.7.1"
      - run:
          name: Package and push chart
          command: |
            CHARTVERSION=$(yq eval '.version' Chart.yaml)
            helm package $CIRCLE_PROJECT_REPONAME
            helm push "${CIRCLE_PROJECT_REPONAME}-${CHARTVERSION}.tgz" "oci://${HELM_REPOADDR}"
            echo "export CHARTVERSION=${CHARTVERSION}" >> $BASH_ENV
  upgrade-deployment:
    docker:
      - image: cimg/base:edge
    steps:
      - gcp-cli/install:
          version: "372.0.0"
      - gcp-cli/initialize
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: $CLUSTER_NAME
          install-kubectl: true
      - run: 
          name: Authenticate with Artifact Registry
          command: |
            cat ${HOME}/gcloud-service-key.json | helm registry login -u _json_key \
              --password-stdin \
              "https://${GOOGLE_COMPUTE_REGION}-docker.pkg.dev"
      - helm/install-helm-client:
          version: "3.7.1"
      - run:
          name: Upgrade deployment
          command: |
            helm upgrade -i $CIRCLE_PROJECT_REPONAME \
              "oci://${HELM_REPOADDR}/${CIRCLE_PROJECT_REPONAME}" \
              --version $CHARTVERSION
  no-op:
    docker:
      - image: cimg/base:edge
    steps:
      - run: echo "No changes required"

workflows:
  version: 2
  production_flow:
    when: <<pipeline.parameters.appVersion>>
    jobs:
      - update-appVersion
      - package-chart:
          requires:
            - update-appVersion
          context: cloudSecrets
      - upgrade-deployment:
          requires:
            - package-chart
          context: cloudSecrets
    when: 
      not: <<pipeline.parameters.appVersion>>
    jobs:
      - no-op
      